title: Standardseite
tabs:
  content:
    columns:
      main:
        width: 3/4
        sections:
          fields:
            type: fields
            fields:
              layout:
                type: layout
                label: Seiteninhalt
                layouts:
                  - "1/1"
                  - "1/2"
                  - "2/3"
                  - "1/2, 1/2"
                  - "1/3, 1/3, 1/3"
                  - "1/4, 1/4, 1/4, 1/4"
                  - "2/3, 1/3"
                  - "1/2, 1/4, 1/4"
                  - "1/3, 2/3"
                  - "1/1, 1/2, 1/2"
                  - "1/1, 1/3, 1/3, 1/3"
                  - "1/1, 1/4, 1/4, 1/4, 1/4"
                  - "1/1, 1/3, 2/3"
                  - "1/1, 2/3, 1/3"
                  - "1/1, 1/2, 1/4, 1/4"
                  - "1/1, 1/2, 1/4, 1/4, 1/1"
                fieldsets:
                  - heading
                  - text
                  - image
                  - list
                  - quote
                  - code
                  - datablock
                  - button
                  - diashow
                  - linklist
                  - logoticker
                  - imageslider
                  - linkslider
                  - pagination
                  - accordion
                  - column_settings
                settings:
                  fields:
                    layout_settings: fields/layout_settings
      sidebar:
        width: 1/4
        sticky: true
        sections:
          pages:
            type: pages
            template: default
            label: Unterseiten
          files:
            type: files
            label: Dateien auf dieser Seite
          meta_fields:
            type: fields
            label: Weitere Inhalte
            fields:
              pexels:
                type: pexels
                label: Pexels
          themepreview:
            type: themepreview
            label: Getting started
