title: Standard Seite
tabs:
  content:
    columns:
      main:
        width: 3/4
        sections:
          fields:
            type: fields
            fields:
              layout: fields/pagelayout
      sidebar:
        width: 1/4
        sections:
          pages:
            type: pages
            template: default
          files:
            type: files
#  seo: seo/page
